baseurl = "https://pchaussalet.github.io/expat-coder/"
languageCode = "fr-fr"
title = "Expat coder"
relativeurls = true
canonifyurls = true
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "expatcoder"
theme = "minimalist"

[params]
    site_author = "Pierre Chaussalet"
    site_description = "Un codeur loin de chez lui."
    location = "SF Bay Area"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/profile.jpg"
    header_background = "img/desk.jpg"
    header_title = "Expat coder"
    copyright = "Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-72736021-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "pchaussalet"
    facebook  = "pchaussalet"
    linkedin  = "pchaussalet"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "pchaussalet"
    gplus     = "pchaussalet"
